image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 5500
    onOpen: ignore
    visibility: public
  - port: 8081
    onOpen: open-browser
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'serving WebSocket' # runs during prebuild
    command: php bin/chat-server.php
  - init: echo 'serving api'
    command: cd api && php -S localhost:3000
  - command: gp await-port 3306 && mysql -u root -h localhost < database/db.sql
  - init: echo 'serving client'
    command: npm i -g http-server && cd client && http-server
